### ISSUE TITLE
[1.21] Crash occurs in single-player by pressing E

### ISSUE THREAD

**Issue by Fossssss** [Wudji/XPlus-2.0-Modpack#10]
**Game Version**
1.21

**Bug Description**
Crash occurs in single-player by pressing E

[错误报告-2024-7-16_12.20.23.zip](https://github.com/user-attachments/files/16243119/-2024-7-16_12.20.23.zip)

java.lang.IllegalStateException: Item group has no page

**Comment by Wudji** [comment]
懒得修，应该只有第一次会崩，暂时不知道为什么
seems that the game only crashes at the first time

**Comment by Wudji** [comment]
https://github.com/emilyploszaj/emi/issues/580

However XPlus is using EMI v1.1.10, this issue need further test...

**Comment by Wudji** [comment]
Fixed by disabling `append-mod-id` in EMI

**Comment by yynsz07** [comment]
1.21依旧会出现这个问题   你需要在安装EMI之前进入游戏打开一次物品栏，然后再安装EMI才行；可以正常按E后再安装新的其他模组也会出现同样的问题还得重复再操作一次才行     你要懒得修算了   感觉还挺麻烦的

**Comment by Wudji** [comment]
> 1.21依旧会出现这个问题 你需要在安装EMI之前进入游戏打开一次物品栏，然后再安装EMI才行；可以正常按E后再安装新的其他模组也会出现同样的问题还得重复再操作一次才行 你要懒得修算了 感觉还挺麻烦的

v6.0.5.1应该修复了这个问题

**Comment by OstiumAxioma** [comment]
该问题在单人模式被修复，但是在服务器上使用创造模式物品栏仍然会导致客户端崩溃（生存模式不会），原因不明
