### ISSUE TITLE
在多人游戏聊天框按上键自动补全时会导致游戏崩溃

### ISSUE THREAD

**Issue by odyy345-u** [Wudji/XPlus-2.0-Modpack#11]
**Game Version**
In which game version does the bug occur?
Note: Old versions are not supported.

1.21
Xplus v6.0.3

**Bug Description**

在聊天框按上键自动补全时会导致游戏崩溃

**Steps to Reproduce**

1.打开任意一个服务器
2.聊天框随便发点东西
3.打开聊天框按上键

**Expected Behavior**

游戏正确触发自动补全

**Screenshots (if applicable)**
If applicable, add screenshots to help explain the problem.

**Crash Logs (if applicable)**
crash-report.txt latest.log

see 
[crash-2024-07-28_14.37.50-client.txt](https://github.com/user-attachments/files/16402467/crash-2024-07-28_14.37.50-client.txt)

**Additional Information**
Any additional information or details that may be helpful.

**Comment by Wudji** [comment]
无法复现，可能与某些缓存文件生成错误有关？
可以尝试禁用XPlusContingameIME

**Comment by odyy345-u** [comment]
禁用XPlusContingameIME问题完美解决
