### ISSUE TITLE
[显示][盔甲条颜色显示]armorchroma 在1.18.1多人模式使用无法进入1.18服务器的游戏

### ISSUE THREAD

**Issue by A8Chann** [Wudji/XPlus-2.0-Modpack#2]
**游戏版本**
该bug出现在哪个游戏版本中？
注：1.7.10 1.10.2 1.11.2 1.14.4版本不受支持
1.18.1
**Bug描述**
[显示][盔甲条颜色显示]armorchroma开启后在多人模式使用无法进入游戏，游戏进程无响应
**如何重现**
使用XPlus 2.0 for Minecraft 1.18.1 (Fabric)（20211212版本）进入游戏，多人游戏，地址v180.minemc.top，进入游戏卡死。
**你认为应该是什么样的**
当然是直接能进
**截图(如果有)**

**崩溃日志(如果有):**
crash-report.txt latest.log

**其他**
更多信息

**Comment by Wudji** [comment]
经测试能正常进入服务器v180.minemc.top，并且能正常穿戴盔甲

**Comment by A8Chann** [comment]
抱歉，是我的自定义物品改了net刷出了盔甲值导致使用该mod崩溃。
