### ISSUE TITLE
1.18.1-20211212版本中的Xaero的世界地图中对低于y=0的位置使用TP功能会卡入下半格方块

### ISSUE THREAD

**Issue by mengyan233** [Wudji/XPlus-2.0-Modpack#3]
**游戏版本**
该bug出现在哪个游戏版本中？
1.18以及1.18.1

**Bug描述**
打开Xaero的世界地图的全屏地图之后，对y0以下的位置使用Teleport Here(TP)功能会卡进所在位置的下一格方块，如果tp的位置只有单层方块则会往下掉落（恼
在Y0往上的位置则正常，Xaero为了防止TP之后卡bug在TP点的Y坐标多加了半格高度
例如我要tp的目标位置高度为y65，则使用世界地图的TP功能会传送到Y65.5的位置
但是在1.18中若TP高度为-20则会传送到-20.5的位置，也就是往下TP（恼

**如何重现**
使用快捷键打开Xaero的世界地图的全屏地图
对Y小于0的目标地点右键
“传送至此处”(Teleport Here)
你进入了下半格方块！！

**你认为应该是什么样的**
我去Xaero的curseforge官网看了一下1.18版本的mini地图已经更新到了21.22.5，世界地图则更新到了1.18.7版本
我们的Xplus1.18.1-20211212版本中的mini地图为21.22.3，世界地图为1.18.4版本
我更新mod版本之后就没有这个问题了
（Xaero's World Map最近一次也是在12号更新的

**截图(如果有)**

**崩溃日志(如果有):**
crash-report.txt latest.log

**其他**
更多信息

**Comment by Wudji** [comment]
将于下个版本中修复

**Comment by Wudji** [comment]
已于1.18.1-fabric-20220103版本中修复
