### ISSUE TITLE
Add CalcMod

### ISSUE THREAD

**Issue by shadeydo** [Wudji/XPlus-2.0-Modpack#5]
**Game Version**
1.20.1

**Suggestion**
Add the mod [CalcMod](https://modrinth.com/mod/calcmod), A simple clientside calculator in the minecraft chat, with extra shortcuts to make life easier. i think it would really fit the "vanilla QoL" vibe of XPlus, as its unintrusive but handy!

**Additional Information**
see a full list of features in the modrinth listing above!

**Comment by Wudji** [comment]
Thank you for your advice! The Calcmod will be included in *XPlus 2.0 based on Minecraft 1.20.2 (Fabric) v5.2.0*, which will be released soon!
