### ISSUE TITLE
macOS14.1（macOS Sonoma）因IMBlocker崩溃

### ISSUE THREAD

**Issue by minimouse0** [Wudji/XPlus-2.0-Modpack#6]
**Game Version**
1.20.2

**Bug Description**
游戏因IMBlocker崩溃，疑似该mod在当前运行环境下不兼容，而且该mod介绍只有兼容Windows和Linux，并没有提及macOS

**Steps to Reproduce**
- 直接导入并运行整合包，游戏崩溃
- 经过排查，发现只禁用IMBlocker后，游戏即可正常运行
- 只启用IMBlocker和其前置fabric-api，游戏崩溃

**Expected Behavior**
可否实现在macOS（darwin）环境下自动禁用该mod

**Crash Logs (if applicable)**
[minecraft-exported-logs-2023-11-08T15-57-50.log](https://github.com/Wudji/XPlus-2.0-Modpack/files/13293930/minecraft-exported-logs-2023-11-08T15-57-50.log)

**Comment by Wudji** [comment]
1.20.4+版本中已换用IngameIME模组，*理论上*已兼容macOS
