### ISSUE TITLE
Can't download caused by wrong SodiumTranslation.zip hashes and file size.

### ISSUE THREAD

**Issue by flezus** [Wudji/XPlus-2.0-Modpack#9]
**Game Version**
In which game version does the bug occur?
1.21 v6.0.2

**Bug Description**
I can't download the modpack in any way.

**Steps to Reproduce**
Try to download the modpack

**Screenshots (if applicable)**
![bug](https://github.com/Wudji/XPlus-2.0-Modpack/assets/88999732/9421c8ef-ff03-4170-8bbc-afa5e232f5e3)

**Crash Logs (if applicable)**
crash-report.txt latest.log

**Additional Information**

**Comment by Wudji** [comment]
Fixed in [v6.0.2.1-fabric-mc1.21](https://modrinth.com/modpack/xplus-2.0-modpack-global/version/v6.0.2.1-fabric-mc1.21)
